### ISSUE TITLE
IDLE not opening multiple .py files

### ISSUE THREAD

**Issue by GolfLord** [python/psf-infra-meta#49]
I'm running Python 3.8  and Mac Os Catalina 10.15.1 When I click a .py file, it will open the shell + editor, However if I try to open a new .py file from my finder window it won't open. The only way I can open another file is through the shell by clicking file - open. I downloaded a folder with containing .py files from the web and I have no issue opening those files from my finder window. It appear to be only files created in my computer.

**Comment by E-Paine** [comment]
Hi @GolfLord. "psf-infra-meta" is a meta-tracker meaning it is (mainly) meant for reporting issues with the normal bug tracker found at [bugs.python.org](https://bugs.python.org/). The content of your message is already on the issue tracker ([message 357661](https://bugs.python.org/msg357661)) and this issue is (granted, slowly) making its way through the system so I would appreciate if you could close this issue. Thanks.
