### ISSUE TITLE
cant open multiple .py files with IDLE

### ISSUE THREAD

**Issue by lbw5216** [python/psf-infra-meta#61]
I do most of my quick editing in IDLE, and it is usually very easy to double-click the icon on my desktop. However, after updating to Catalina, I can no longer open more than one .py file in IDLE at a time. Via double clicking or left click-open with. The only way I can have two files open at the same time is by going into IDLE-file-open. Also, scrolling has become more difficult inside these windows since opening. I am using python 3.8 and macOS Catalina 10.15.4

**Comment by emilymittleman** [comment]
I'm having this same exact issue with Catalina using python 3.8-- I had previously installed python 2.7 and 3.7 a long time ago to run some programs that had features which were deprecated in 3.8, and since I was having this issue with 3.8, I tried seeing if I would run into the same problem with earlier versions of python. I tried opening files with the earlier versions, and experienced the same issues, so the problem doesn't have anything to do with the python version, it must be the new macOS update. Unfortunately, I haven't found a solution yet.

**Comment by E-Paine** [comment]
Thank you for the report, but this issue has already been reported in [issue 49](https://github.com/python/psf-infra-meta/issues/49#issuecomment-662913511). Quoting my reply there:

> ... "psf-infra-meta" is a meta-tracker meaning it is (mainly) meant for reporting issues with the normal bug tracker found at [bugs.python.org](https://bugs.python.org). The content of your message [the original message on issue 49] is already on the issue tracker ([message 357661](https://bugs.python.org/msg357661)) and this issue is (granted, slowly) making its way through the system so I would appreciate if you could close this issue. Thanks.
