### ISSUE TITLE
Problem when use "or" with "in"

### ISSUE THREAD

**Issue by lavoie005** [python/psf-infra-meta#63]
We always get true

str = 'abcdefg'
if 'h' or 'p' in str:
    print('true')
else:
    print('false')

**Comment by E-Paine** [comment]
Please note that `'h' or 'p' in str` is equivalent to `'h' or ('p' in str)` instead of `'h' in str or 'p' in str` (where `'h'` gives `True` because it is not an empty string). Please note that "psf-infra-meta" is a meta-tracker meaning it is (mainly) meant for reporting issues with the normal bug tracker found at [bugs.python.org](https://bugs.python.org).

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
