### ISSUE TITLE
Python 3.8.5 can't save file

### ISSUE THREAD

**Issue by pickerstick** [python/psf-infra-meta#78]
I tried opening a python file(editited in 3.8.1,opening in 3.8.5) by using MOUSE-RIGHT+e+e and the editor showed up but I can't save file!
Opening a new file by MENU/FILE/New Window works properly and is savable but can't save later using method written above.
HELP!

**Comment by E-Paine** [comment]
Thank you for reporting this bug. It has already been fixed in [issue 41373](https://bugs.python.org/issue41373) just over a month ago, and is already available in the 3.9 release candidate (though will only be available for the 3.8 branch from 3.8.6). In the future, please use [bugs.python.org](bugs.python.org) to report problems as this tracker is meant for reporting bugs with that system. Again, thank you for reporting this bug, but I would appreciate if you could close this issue.

**Comment by matrixise** [comment]
@ewdurbin Could you close this one? Thanks
